import type { NextPage } from 'next'
import Head from 'next/head'
import styles from 'src/styles/Sample.module.scss'
import fetchData from 'src/utility/fetchData'

const getSample = async () => {
  const res = await fetchData('get', process.env.API_DOMAIN + '/get_sample', {
    params: {
      username: 'hoge',
    },
  })
  console.log(res)
}
const postSample = async () => {
  const res = await fetchData('post', process.env.API_DOMAIN + '/post_sample', {
    params: {
      username: 'fuga',
    },
  })
  console.log(res)
}

const MockSample: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mock Sample</title>
        <meta name='description' content='Generated by Mock Sample' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Mock Samples for{' '}
          <a href='https://mswjs.io/' target='_blank'>
            MSW
          </a>
        </h1>

        <div className={styles.grid}>
          <div onClick={getSample} className={styles.card}>
            <h2>GetSample</h2>
            <p>QUERY: username</p>
          </div>
          <div onClick={postSample} className={styles.card}>
            <h2>PostSample</h2>
            <p>QUERY: username</p>
          </div>
        </div>
      </main>
    </div>
  )
}

export default MockSample
