import type { NextPage } from 'next'
import Head from 'next/head'
import styles from 'src/styles/Sample.module.scss'
import fetchData from 'src/utility/fetchData'
import { useQuery, useMutation } from '@tanstack/react-query'

var latestId = 0
const getUserList = async () => {
  const res = await fetchData('get', process.env.API_DOMAIN + '/user_sample')
  console.log(res)
  return res
}
const postSample = async () => {
  const res = await fetchData('post', process.env.API_DOMAIN + '/user_sample', {
    params: {
      id: String(latestId + 1),
      username: 'John',
    },
  })
  latestId++
  console.log(res)
}
const putSample = async () => {
  const res = await fetchData('put', process.env.API_DOMAIN + '/user_sample', {
    params: {
      id: String(latestId),
      username: 'Alex',
    },
  })
  console.log(res)
}

const QuerySample: NextPage = () => {
  const { data, refetch } = useQuery(['user'], () => getUserList())
  const create = useMutation(postSample, {
    onSuccess: () => refetch(),
  })
  const createUser = () => create.mutate()
  const mutation = useMutation(putSample, {
    onSuccess: () => refetch(),
  })
  const updateUser = () => mutation.mutate()

  return (
    <div className={styles.container}>
      <Head>
        <title>Mock Sample</title>
        <meta name='description' content='Generated by Mock Sample' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Mock Samples for{' '}
          <a href='https://mswjs.io/' target='_blank'>
            MSW
          </a>
        </h1>
        <h2>
          {data &&
            Array.isArray(data) &&
            data.map((user: Record<string, string>) => user.username).join(', ')}
        </h2>
        <div className={styles.grid}>
          <div onClick={getUserList} className={styles.card}>
            <h2>GetSample</h2>
          </div>
          <div onClick={createUser} className={styles.card}>
            <h2>PostSample</h2>
          </div>
          <div onClick={updateUser} className={styles.card}>
            <h2>PutSample</h2>
          </div>
        </div>
      </main>
    </div>
  )
}

export default QuerySample
